name: log github events

on:
  push:
    branches: [main, master, pipfile-experiment]
  pull_request:
    types: [opened, closed]
    branches: [main, master, pipfile-experiment]

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PIPENV_PIPFILE: .github/workflows/Pipfile
      GITHUB_LOGIN: ${{ github.actor }}
      COMMITS: ${{ toJSON(github.event.commits) }}
      REPOSITORY_URL: https://github.com/${{ github.repository }}
      EVENT_TYPE: ${{ github.event_name }}
      EVENT_ACTION: ${{ github.event.action }}
      PR_MERGED: ${{ github.event.pull_request.merged }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "^3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
          pipenv install
      - name: Log pull request opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          pipenv run gitcommitlogger \
            -r $REPOSITORY_URL \
            -t pull_request_opened \
            -d $PR_CREATED_AT \
            -un $GITHUB_LOGIN \
            -o commit_stats.csv \
            -v
      - name: Log pull request closed and merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo $COMMITS > commits.json
          cat commits.json
          pipenv run gitcommitlogger \
            -r $REPOSITORY_URL \
            -t pull_request_merged \
            -d $PR_CLOSED_AT \
            -un $GITHUB_LOGIN \
            -i commits.json \
            -o commit_stats.csv \
            -v
      - name: Log pull request closed without merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
        run: |
          pipenv run gitcommitlogger \
            -r $REPOSITORY_URL \
            -t pull_request_closed \
            -d $PR_CLOSED_AT \
            -un $GITHUB_LOGIN \
            -o commit_stats.csv \
            -v
      - name: Log push
        if: github.event_name == 'push'
        run: |
          echo $COMMITS > commits.json
          cat commits.json
          pipenv run gitcommitlogger \
            -r $REPOSITORY_URL \
            -t $EVENT_TYPE \
            -i commits.json \
            -o commit_stats.csv \
            -v
